package com.sankhya.hybridsaga.api;

import java.util.Optional;

/**
 * A read-only snapshot of the pipeline's shared state.
 * <p>
 * This interface provides access to the results generated by previously completed components.
 * By design, it exposes no mutation methods (there is no {@code put}). The pipeline engine
 * handles state updates internally, ensuring that components cannot accidentally overwrite or
 * corrupt the shared context.
 *
 * <h2>Retrieval Strategies</h2>
 * To support different orchestration flows, the context offers two distinct lookup models:
 * <ul>
 * <li><strong>Strict ({@link #require}):</strong> Throws an exception if the value is missing.
 * Use this when a downstream component fundamentally cannot function without an upstream result.</li>
 * <li><strong>Lenient ({@link #find}):</strong> Returns an {@link Optional}. Use this when an
 * upstream result is optional, or when branching logic depends on whether a prior step executed.</li>
 * </ul>
 *
 * <h2>Type-Safe Downcasting</h2>
 * Because the pipeline stores results from diverse components, the underlying map holds untyped objects.
 * To prevent {@code @SuppressWarnings("unchecked")} pollution in user code, this API requires a
 * {@link Class} token. The engine safely performs the cast and throws a clear
 * {@link ContextTypeMismatchException} on failure, rather than a raw {@link ClassCastException}
 * deep within component logic.
 * <p>
 * <em>Tip:</em> Due to Java's type erasure, a {@code Class} token cannot represent generic collections
 * (like {@code List<Order>}). If a component produces a collection, wrap it in a custom {@code record}
 * to maintain strict type safety.
 *
 * <h2>Null Results vs. Missing Results</h2>
 * If a component completes successfully but intentionally returns {@code null}, it is still considered
 * "executed." In this scenario:
 * <ul>
 * <li>{@link #contains(OperationName)} returns {@code true}.</li>
 * <li>{@link #require(OperationName, Class)} returns {@code null} (logs a warning).</li>
 * <li>{@link #find(OperationName, Class)} returns {@link Optional#empty()} (logs a warning).</li>
 * </ul>
 */
public interface ContextView {

    /**
     * Retrieves the strictly required result of a prior operation, safely cast to the requested type.
     *
     * @param operation the unique name of the upstream component that produced the result
     * @param type      the expected class type of the result
     * @param <T>       the generic type of the result
     * @return the stored value (which may be {@code null} if the component explicitly returned null)
     * @throws MissingOperationOutputException if no execution record exists for the specified operation
     * @throws ContextTypeMismatchException    if the stored value cannot be assigned to the requested type
     */
    <T> T require(OperationName operation, Class<T> type);

    /**
     * Safely retrieves an optional result from a prior operation.
     *
     * @param operation the unique name of the upstream component that produced the result
     * @param type      the expected class type of the result
     * @param <T>       the generic type of the result
     * @return an {@link Optional} containing the value, or {@link Optional#empty()} if the operation
     * did not run or intentionally returned {@code null}
     * @throws ContextTypeMismatchException if a value exists but cannot be assigned to the requested type
     */
    <T> Optional<T> find(OperationName operation, Class<T> type);

    /**
     * Checks if a specific operation has completed and recorded a result in the context.
     * <p>
     * Note: This returns {@code true} even if the operation successfully completed but returned {@code null}.
     *
     * @param operation the operation name to verify
     * @return {@code true} if the operation's output is recorded; {@code false} otherwise
     */
    boolean contains(OperationName operation);

    // ==============================================================================================
    // String-Keyed Convenience Methods
    // These default methods provide syntactic sugar, automatically wrapping standard strings into
    // strongly-typed OperationName records to keep component logic clean.
    // ==============================================================================================

    /**
     * Convenience overload for {@link #require(OperationName, Class)}.
     */
    default <T> T require(String operation, Class<T> type) {
        return require(OperationName.of(operation), type);
    }

    /**
     * Convenience overload for {@link #find(OperationName, Class)}.
     */
    default <T> Optional<T> find(String operation, Class<T> type) {
        return find(OperationName.of(operation), type);
    }

    /**
     * Convenience overload for {@link #contains(OperationName)}.
     */
    default boolean contains(String operation) {
        return contains(OperationName.of(operation));
    }
}