package com.sankhya.hybridsaga.api;

/**
 * The execution environment provided to a pipeline component during its forward phase.
 * <p>
 * Rather than passing multiple loose arguments to a component, the engine encapsulates all
 * necessary execution state—such as the master payload and prior results—into this single
 * context object.
 *
 * @param <M> the type of the master request flowing through the pipeline
 */
public interface ForwardContext<M> {

    /**
     * Returns the primary payload that initiated the pipeline execution.
     * <p>
     * Every component in the pipeline receives the exact same instance of this request.
     * By convention, components must treat this object as strictly read-only and immutable.
     *
     * @return the master request
     */
    M masterRequest();

    /**
     * Provides a read-only snapshot of the results produced by previously completed components.
     * <p>
     * Components use this view to consume data generated by upstream steps in the pipeline.
     * <p>
     * <strong>Concurrency Warning:</strong> If the pipeline engine executes steps in parallel,
     * it is unsafe to attempt to read the output of a sibling component running in the same
     * parallel group, as there are no strict ordering guarantees. Components must only rely
     * on data produced by strictly prior, fully completed steps.
     *
     * @return a read-only view of prior component outputs
     */
    ContextView context();
}